// src/components/Settings.jsx
import { useState, useEffect } from 'preact/hooks';
import '../css/settings.css';
import Page from './Page';
import { PageType } from '../constants/pageTypes';
import { useSettings } from '../context/SettingsContext';
import { settingsOptions } from '../constants/settingsOptions';
import { Link } from 'wouter';
import { SpellbookDB } from '../utils/db';

export default function Settings() {
    const [isDoublePage, setIsDoublePage] = useState(window.innerWidth > window.innerHeight);
    const { settings, updateSetting } = useSettings();
    const [newSpellbookName, setNewSpellbookName] = useState('');
    const [spellbookName, setSpellbookName] = useState(settings[settingsOptions.CURRENT_SPELLBOOK_DB]);
    const [fontAddition, setFontAddition] = useState(settings[settingsOptions.FONTADDITION] || 0);
    const [spellbookList, setSpellbookList] = useState(settings[settingsOptions.SPELLBOOK_LIST] || []);
    const [needsRefresh, setNeedsRefresh] = useState(false);

    const refreshData = async () => {
        const list = await SpellbookDB.listAllSpellbooks();
        await updateSetting(settingsOptions.SPELLBOOK_LIST, list);
        const currentBook = await SpellbookDB.getCurrentSpellbookName();
        await updateSetting(settingsOptions.CURRENT_SPELLBOOK_DB, currentBook);
        setNeedsRefresh(false);
    };

    useEffect(() => {
        refreshData();
        loadCustomFont();
    }, [needsRefresh]);

    useEffect(() => {
        setSpellbookName(settings[settingsOptions.CURRENT_SPELLBOOK_DB]);
        setFontAddition(settings[settingsOptions.FONTADDITION] || 0);
        setSpellbookList(settings[settingsOptions.SPELLBOOK_LIST] || []);
    }, [settings]);

    // Double page detection based on window size
    useEffect(() => {
        const handleResize = () => {
            setIsDoublePage(window.innerWidth > window.innerHeight);
        };
        window.addEventListener('resize', handleResize);
        return () => window.removeEventListener('resize', handleResize);
    }, []);

    const handleExportSpellbook = async () => {
        try {
            const data = await SpellbookDB.exportSpellbookData();
            const blob = new Blob([JSON.stringify(data)], { type: 'application/json' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${settings[settingsOptions.CURRENT_SPELLBOOK_DB]}.json.spellbook`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        } catch (error) {
            console.error('Export failed:', error);
        }
    };

    const [importData, setImportData] = useState(null);
    const [importFile, setImportFile] = useState(null);

    const handleImportSpellbookSelect = async (event) => {
        try {
            const file = event.target.files[0];
            if (!file) return;
            setImportFile(file);

            const reader = new FileReader();
            reader.onload = async (e) => {
                const data = JSON.parse(e.target.result);
                setImportData(data);
            };
            reader.readAsText(file);
        } catch (error) {
            console.error('Import failed:', error);
            setImportData(null);
            setImportFile(null);
        }
    };

    const handleImportConfirm = async () => {
        try {
            if (!importData) return;

            // Generate unique name for the imported spellbook
            const uniqueName = await SpellbookDB.generateUniqueSpellbookName(importData.name || 'Imported Spellbook');

            // Create new spellbook and import data
            await SpellbookDB.createNewSpellbook(uniqueName);
            await SpellbookDB.importSpellbookData(importData);

            // Clear import state
            setImportData(null);
            setImportFile(null);
            setNeedsRefresh(true);
        } catch (error) {
            console.error('Import failed:', error);
        }
    };

    const handleSpellbookNameChange = async () => {
        try {
            const currentName = settings[settingsOptions.CURRENT_SPELLBOOK_DB];
            if (currentName !== spellbookName) {
                await SpellbookDB.renameSpellbook(currentName, spellbookName);
                setNeedsRefresh(true);
            }
        } catch (error) {
            console.error('Failed to change spellbook name:', error);
        }
    };

    const [currentFont, setCurrentFont] = useState(null);

    useEffect(() => {
        const loadFont = async () => {
            const fontData = await SpellbookDB.getFont();
            setCurrentFont(fontData);
        };
        loadFont();
    }, []);

    const { loadCustomFont } = useSettings();
    const handleFontUpload = async (event) => {
        const file = event.target.files[0];
        if (!file) return;

        try {
            const reader = new FileReader();
            reader.onload = async (e) => {
                const fontData = {
                    data: e.target.result,
                    name: file.name
                };
                await SpellbookDB.saveFont(fontData);
                setCurrentFont(fontData);
                await loadCustomFont();
            };
            reader.readAsDataURL(file);
        } catch (error) {
            console.error('Failed to upload font:', error);
        }
    };

    const handleRemoveFont = async () => {
        try {
            await SpellbookDB.removeFont();
            setCurrentFont(null);
            await loadCustomFont();
        } catch (error) {
            console.error('Failed to remove font:', error);
        }
    };

    const handleCreateNewSpellbook = async () => {
        if (!newSpellbookName) return;
        try {
            await SpellbookDB.createNewSpellbook(newSpellbookName);
            await updateSetting(settingsOptions.CURRENT_SPELLBOOK_DB, newSpellbookName);
            setNewSpellbookName('');
            setNeedsRefresh(true);
        } catch (error) {
            console.error('Failed to create new spellbook:', error);
        }
    };

    const handleFontAdditionChange = async (value) => {
        const newValue = parseInt(value) || 0;
        setFontAddition(newValue);
        await updateSetting(settingsOptions.FONTADDITION, newValue);
        await loadCustomFont();
    };

    const handleAnimationToggle = async (checked) => {
        await updateSetting(settingsOptions.ANIMATION, checked);
    };

    const handlePageFitToggle = async (checked) => {
        await updateSetting(settingsOptions.PAGEFIT, checked);
    };

    const handleDeleteSpellbook = async (name) => {
        if (window.confirm(`Are you sure you want to delete the spellbook "${name}"?`)) {
            try {
                await SpellbookDB.deleteSpellbook(name);
                setNeedsRefresh(true);
            } catch (error) {
                console.error('Failed to delete spellbook:', error);
            }
        }
    };

    return (
        <>
            <Page pageType={PageType.TITLE}>
                <div className='text-overlay' id="title">
                    Settings
                </div>
                <div className='settings__container'>
                    <div>
                        Spellbook Settings
                        {/* TODO: change hr look with css */}
                        <hr className='settings__hr-break' />
                    </div>
                    {/* Settings for the currently selected spellbook */}
                    <div className='settings__container-line'>
                        <label className='settings__file-input-label' for="spellbookName">
                            Name:
                            <br />
                            <input
                                type='text'
                                value={spellbookName}
                                id='spellbookName'
                                onChange={(e) => setSpellbookName(e.target.value)}
                                className='settings__input'
                            />
                        </label>
                        <button className='settings__interact' onClick={handleSpellbookNameChange}>Change</button>
                    </div>
                    <div className='settings__container-line'>
                        <label className='settings__file-input-label'>
                            Spellbook Font
                            <input
                                type='file'
                                accept=".ttf,.otf,.woff,.woff2"
                                onChange={handleFontUpload}
                                className='settings__file-input'
                            />
                        </label>
                        <button className='settings__interact' onClick={handleRemoveFont}>X</button>
                    </div>
                    <div>Change Spellbook
                        <div>
                            <div>Current: <i>{settings[settingsOptions.CURRENT_SPELLBOOK_DB]}</i></div>
                            {settings[settingsOptions.SPELLBOOK_LIST]?.filter(name =>
                                name !== settings[settingsOptions.CURRENT_SPELLBOOK_DB]
                            ).map((name) => (
                                <div key={name} className='settings__spellbook-item'>
                                    <button onClick={async () => {
                                        await SpellbookDB.switchSpellbook(name);
                                        setNeedsRefresh(true);
                                    }}
                                        className='settings__spellbook-button'>
                                        {name}
                                    </button>
                                    <button
                                        className="settings__interact"
                                        onClick={() => handleDeleteSpellbook(name)}
                                    >
                                        Delete
                                    </button>
                                </div>
                            ))}
                        </div>
                    </div>
                    <div className='settings__container-line'>
                        <label for="newSpellbookName">
                            Create new spellbook
                            <input
                                type='text'
                                id="newSpellbookName"
                                value={newSpellbookName}
                                className='settings__input'
                                onChange={(e) => setNewSpellbookName(e.target.value)}
                            />
                        </label>
                        <button className='settings__interact' onClick={handleCreateNewSpellbook}>Add</button>
                    </div>
                    <div>
                        <label for="exportSpellbook">Export Spellbook</label>
                        <br />
                        <button id="exportSpellbook" className='settings__interact' onClick={handleExportSpellbook}>Export</button>
                    </div>
                    <div>
                        <label for="importSpellbook">Import Spellbook</label>
                        <input
                            type="file"
                            accept=".spellbook,.json"
                            id="importSpellbook"
                            onChange={handleImportSpellbookSelect}
                            className='settings__file-input'
                        />
                        {importData && (
                            <div>
                                <p>Import "{importData.name || 'Unnamed Spellbook'}"?</p>
                                <button onClick={handleImportConfirm}>Confirm Import</button>
                                <button onClick={() => {
                                    setImportData(null);
                                    setImportFile(null);
                                }}>Cancel</button>
                            </div>
                        )}
                    </div>

                    <div>
                        General Settings
                        <hr className='settings__hr-break' />
                    </div>
                    <label>
                        Fontsize:
                        <input
                            type='number'
                            value={fontAddition}
                            onChange={(e) => handleFontAdditionChange(e.target.value)}
                            className='settings__input'
                        />
                    </label>
                    <label>
                        Animations:
                        <input
                            type='checkbox'
                            checked={settings[settingsOptions.ANIMATION]}
                            onChange={(e) => handleAnimationToggle(e.target.checked)}
                        />
                    </label>
                    <label>
                        Page Fit:
                        <input
                            type='checkbox'
                            checked={settings[settingsOptions.PAGEFIT]}
                            onChange={(e) => handlePageFitToggle(e.target.checked)}
                        />
                    </label>
                    <div className='settings__container-after'></div>
                </div>
                <Link to='/' className='interact settings__home-button' />
                <button className='interact settings__font-button'></button>
                <button className='interact settings__edit-button'></button>
            </Page >

            {isDoublePage &&
                <Page pageType={PageType.SPELLRIGHT}>
                </Page>
            }
        </>
        // <div className="container">
        //     {/* Page 1 */}
        //     <div className="svg-overlay page-1">
        //         <img className="page-img" src="assets/imgs/spellbook_cover.svg" alt="First page of DnD book" />
        //         <button className="interact" id="p1-next" onClick={nextPage}></button>

        //         {/* Nav */}
        //         <Link href="/settings">
        //             <button className="interact settings"></button>
        //         </Link>
        //         <Link href="/">
        //             <button className="interact home"></button>
        //         </Link>
        //         <button className="interact font" onClick={toggleFont}></button>

        //         <div className="settingsBlock">
        //             <div>
        //                 <button
        //                     className="settings-input"
        //                     type="number"
        //                     id="exportDB"
        //                     onClick={exportSpellPageDB}
        //                 >
        //                     Export spellbook
        //                 </button>
        //                 <input
        //                     className="settings-input"
        //                     type="file"
        //                     id="fileInput"
        //                     accept=".json"
        //                     onChange={(e) => importSpellPageDB(e.target.files[0])}
        //                 />
        //             </div>
        //             <label htmlFor="font_addition">
        //                 Font Addition:
        //                 <input
        //                     className="settings-input"
        //                     type="number"
        //                     id="font_addition"
        //                     value={fontAddition}
        //                     onChange={(e) => updateFontAddition(e.target.value)}
        //                 />
        //             </label>
        //             <label htmlFor="page_fit">
        //                 Page Fit:
        //                 <input
        //                     className="settings-input"
        //                     type="checkbox"
        //                     id="page_fit"
        //                     checked={pageFit}
        //                     onChange={(e) => updatePageFit(e.target.checked)}
        //                 />
        //             </label>
        //             <label htmlFor="animation">
        //                 Animation:
        //                 <input
        //                     className="settings-input"
        //                     type="checkbox"
        //                     id="animation"
        //                     checked={animation}
        //                     onChange={(e) => updateAnimation(e.target.checked)}
        //                 />
        //             </label>
        //             <label htmlFor="local_font">
        //                 Local Font:
        //                 <input
        //                     className="settings-input"
        //                     type="file"
        //                     id="local_font"
        //                     accept=".ttf,.otf,.woff,.woff2"
        //                     onChange={(e) => updateLocalFont(e.target.files[0])}
        //                 />
        //                 <button className="remove-font-button" onClick={removeLocalFont}>X</button>
        //             </label>
        //             <label htmlFor="current_spellbook_db">Select Spellbook DB:</label>
        //         </div>
        //     </div>

        //     {/* Page 2 */}
        //     <div className="svg-overlay page-2">
        //         <img className="page-img" src="assets/imgs/spellbook_cover_right_page.svg" alt="Second page of DnD book" />
        //         <button className="interact" id="p2-previous" onClick={previousPage}></button>
        //     </div>
        // </div>
    );
}

// src/components/Settings.svelte
<script>
    import Page from "./Page.svelte";
    import { PageType } from "../constants/pageType";
    import { getSettingsContext } from "../context/settings.svelte.js";
    import { settingsOptions } from "../constants/settingsOptions";
    import { PageDB } from "../utils/db";

    const settings = getSettingsContext();

    let newSpellbookName = $state("");
    let spellbookName = $state(
        settings.values[settingsOptions.CURRENT_SPELLBOOK_DB],
    );
    let fontAddition = $state(
        settings.values[settingsOptions.FONTADDITION] || 0,
    );
    let importData = $state(null);
    let importFile = $state(null);
    let currentFont = $state(null);

    // Keep local editable fields in sync whenever settings change elsewhere
    $effect(() => {
        spellbookName = settings.values[settingsOptions.CURRENT_SPELLBOOK_DB];
        fontAddition = settings.values[settingsOptions.FONTADDITION] || 0;
    });

    // Double page detection
    // $effect(() => {
    //     const handleResize = () => {
    //         isDoublePage = window.innerWidth > window.innerHeight;
    //     };
    //     window.addEventListener("resize", handleResize);
    //     return () => window.removeEventListener("resize", handleResize);
    // });

    // Load current font once on mount
    $effect(() => {
        (async () => {
            currentFont = await PageDB.getFont();
        })();
    });

    async function refreshData() {
        const list = await PageDB.listAllSpellbooks();
        await settings.set(settingsOptions.SPELLBOOK_LIST, list);
        const currentBook = await PageDB.getCurrentSpellbookName();
        await settings.set(settingsOptions.CURRENT_SPELLBOOK_DB, currentBook);
    }

    async function handleExportSpellbook() {
        try {
            const data = await PageDB.exportSpellbookData();
            const blob = new Blob([JSON.stringify(data)], {
                type: "application/json",
            });
            const url = URL.createObjectURL(blob);
            const a = document.createElement("a");
            a.href = url;
            a.download = `${settings.values[settingsOptions.CURRENT_SPELLBOOK_DB]}.json.spellbook`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        } catch (error) {
            console.error("Export failed:", error);
        }
    }

    async function handleImportSpellbookSelect(event) {
        try {
            const file = event.target.files[0];
            if (!file) return;
            importFile = file;

            const reader = new FileReader();
            reader.onload = (e) => {
                importData = JSON.parse(e.target.result);
            };
            reader.readAsText(file);
        } catch (error) {
            console.error("Import failed:", error);
            importData = null;
            importFile = null;
        }
    }

    async function handleImportConfirm() {
        try {
            if (!importData) return;

            const uniqueName = await PageDB.generateUniqueSpellbookName(
                importData.name || "Imported Spellbook",
            );

            await PageDB.createNewSpellbook(uniqueName);
            await PageDB.importSpellbookData(importData);

            importData = null;
            importFile = null;
            await refreshData();
            await settings.loadCustomFont();
        } catch (error) {
            console.error("Import failed:", error);
        }
    }

    function handleImportCancel() {
        importData = null;
        importFile = null;
    }

    async function handleSpellbookNameChange() {
        try {
            const currentName =
                settings.values[settingsOptions.CURRENT_SPELLBOOK_DB];
            if (currentName !== spellbookName) {
                await PageDB.renameSpellbook(currentName, spellbookName);
                await refreshData();
                await settings.loadCustomFont();
            }
        } catch (error) {
            console.error("Failed to change spellbook name:", error);
        }
    }

    async function handleFontUpload(event) {
        const file = event.target.files[0];
        if (!file) return;

        try {
            const reader = new FileReader();
            reader.onload = async (e) => {
                const fontData = {
                    data: e.target.result,
                    name: file.name,
                };
                await PageDB.saveFont(fontData);
                currentFont = fontData;
                await settings.loadCustomFont();
            };
            reader.readAsDataURL(file);
        } catch (error) {
            console.error("Failed to upload font:", error);
        }
    }

    async function handleRemoveFont() {
        try {
            await PageDB.removeFont();
            currentFont = null;
            await settings.loadCustomFont();
        } catch (error) {
            console.error("Failed to remove font:", error);
        }
    }

    async function handleCreateNewSpellbook() {
        if (!newSpellbookName) return;
        try {
            await PageDB.createNewSpellbook(newSpellbookName);
            await settings.set(
                settingsOptions.CURRENT_SPELLBOOK_DB,
                newSpellbookName,
            );
            newSpellbookName = "";
            await refreshData();
        } catch (error) {
            console.error("Failed to create new spellbook:", error);
        }
    }

    async function handleFontAdditionChange(value) {
        const newValue = parseInt(value) || 0;
        fontAddition = newValue;
        await settings.set(settingsOptions.FONTADDITION, newValue);
        await settings.loadCustomFont();
    }

    async function handleAnimationToggle(checked) {
        await settings.set(settingsOptions.ANIMATION, checked);
    }

    async function handlePageFitToggle(checked) {
        await settings.set(settingsOptions.PAGEFIT, checked);
    }

    async function handleDeleteSpellbook(name) {
        if (
            window.confirm(
                `Are you sure you want to delete the spellbook "${name}"?`,
            )
        ) {
            try {
                await PageDB.deleteSpellbook(name);
                await refreshData();
            } catch (error) {
                console.error("Failed to delete spellbook:", error);
            }
        }
    }
</script>

<Page pageType={PageType.TITLE_RIGHT}>
    <div class="text-overlay" id="title">Settings</div>
    <div class="container right-page-offset">
        <div class="container-line">
            <label class="file-input-label" for="spellbookName">
                Name:
                <br />
                <input
                    type="text"
                    bind:value={spellbookName}
                    id="spellbookName"
                    class="input"
                />
            </label>
            <button class="settings-button" onclick={handleSpellbookNameChange}
                >Change</button
            >
        </div>

        <div class="container-line">
            <label class="file-input-label">
                Spellbook Font
                <input
                    type="file"
                    accept=".ttf,.otf,.woff,.woff2"
                    onchange={handleFontUpload}
                    class="file-input"
                />
            </label>
            <button class="settings-button" onclick={handleRemoveFont}>X</button
            >
        </div>

        <div>
            Change Spellbook
            <div>
                <div>
                    Current: <i
                        >{settings.values[
                            settingsOptions.CURRENT_SPELLBOOK_DB
                        ]}</i
                    >
                </div>
                {#each (settings.values[settingsOptions.SPELLBOOK_LIST] || []).filter((name) => name !== settings.values[settingsOptions.CURRENT_SPELLBOOK_DB]) as name (name)}
                    <div class="spellbook-item">
                        <button
                            class="spellbook-button"
                            onclick={async () => {
                                await PageDB.switchSpellbook(name);
                                await refreshData();
                                await settings.loadCustomFont();
                                // reload page without param
                                window.location.href =
                                    window.location.origin +
                                    window.location.pathname;
                            }}
                        >
                            {name}
                        </button>
                        <button
                            class="settings-button"
                            onclick={() => handleDeleteSpellbook(name)}
                        >
                            Delete
                        </button>
                    </div>
                {/each}
            </div>
        </div>

        <div class="container-line">
            <label for="newSpellbookName">
                Create new spellbook
                <input
                    type="text"
                    id="newSpellbookName"
                    bind:value={newSpellbookName}
                    class="input"
                />
            </label>
            <button class="settings-button" onclick={handleCreateNewSpellbook}
                >Add</button
            >
        </div>

        <div>
            <label for="exportSpellbook">Export Spellbook</label>
            <br />
            <button
                id="exportSpellbook"
                class="settings-button"
                onclick={handleExportSpellbook}>Export</button
            >
        </div>

        <div>
            <label for="importSpellbook">Import Spellbook</label>
            <input
                type="file"
                accept=".spellbook,.json"
                id="importSpellbook"
                onchange={handleImportSpellbookSelect}
                class="file-input"
            />
            {#if importData}
                <div>
                    <p>Import "{importData.name || "Unnamed Spellbook"}"?</p>
                    <button onclick={handleImportConfirm}>Confirm Import</button
                    >
                    <button onclick={handleImportCancel}>Cancel</button>
                </div>
            {/if}
        </div>

        <div>
            General Settings
            <hr class="hr-break" />
        </div>

        <label>
            Fontsize:
            <input
                type="number"
                value={fontAddition}
                oninput={(e) => handleFontAdditionChange(e.target.value)}
                class="input"
            />
        </label>

        <label>
            Animations:
            <input
                type="checkbox"
                checked={settings.values[settingsOptions.ANIMATION]}
                onchange={(e) => handleAnimationToggle(e.target.checked)}
            />
        </label>

        <label>
            Page Fit:
            <input
                type="checkbox"
                checked={settings.values[settingsOptions.PAGEFIT]}
                onchange={(e) => handlePageFitToggle(e.target.checked)}
            />
        </label>

        <div class="container-after"></div>
    </div>
</Page>

<style>
    .text-overlay {
        position: absolute;
        font-size: var(--reactive-font-size);
        margin: 0;
        overflow-x: auto;
        white-space: nowrap;
        margin-left: calc(var(--unit-width) * -2);

        padding-left: calc(var(--unit-width) * 2);

        -ms-overflow-style: none;
        scrollbar-width: none;

        /* TODO: gradient on the left */

        -webkit-mask-image: linear-gradient(
            to right,
            rgba(0, 0, 0, 0),
            rgba(0, 0, 0, 0.3) 3%,
            rgba(0, 0, 0, 1) 6%,
            rgba(0, 0, 0, 1) 85%,
            rgba(0, 0, 0, 0)
        );
        mask-image: linear-gradient(
            to right,
            rgba(0, 0, 0, 0),
            rgba(0, 0, 0, 0.3) 3%,
            rgba(0, 0, 0, 1) 6%,
            rgba(0, 0, 0, 1) 85%,
            rgba(0, 0, 0, 0)
        );
        align-content: center;

        &::after {
            content: "";
            width: 20%;
            padding-left: 3vh;
        }

        /* &::before {
        content: '';
        width: 20%;
        padding-right: 3vh;
    } */

        &::-webkit-scrollbar {
            display: none;
        }
    }

    .container {
        position: absolute;
        width: calc(var(--unit-width) * 92);
        height: calc(var(--unit-height) * 140);
        left: calc(var(--unit-width) * 23);
        top: calc(var(--unit-height) * 32);
        font-size: var(--reactive-font-size);
        padding-top: calc(var(--unit-height) * 6);

        display: flex;
        flex-direction: column;
        gap: calc(var(--unit-height) * 5);
        overflow-y: auto;
        -ms-overflow-style: none;
        scrollbar-width: none;
        -webkit-mask-image: linear-gradient(
            to bottom,
            rgba(0, 0, 0, 0),
            rgba(0, 0, 0, 0.2) calc(var(--unit-height) * 3),
            rgba(0, 0, 0, 1) calc(var(--unit-height) * 10),
            rgba(0, 0, 0, 1) 90%,
            rgba(0, 0, 0, 0)
        );
        mask-image: linear-gradient(
            to bottom,
            rgba(0, 0, 0, 0),
            rgba(0, 0, 0, 0.2) calc(var(--unit-height) * 3),
            rgba(0, 0, 0, 1) calc(var(--unit-height) * 10),
            rgba(0, 0, 0, 1) 90%,
            rgba(0, 0, 0, 0)
        );
    }

    .container > * {
        max-width: 100%;
        box-sizing: border-box;
        overflow-wrap: break-word;
        overflow-wrap: anywhere;
        justify-content: space-between;
    }

    .container-line {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .input {
        border: none;
        background: #0001;
        font-size: var(--reactive-font-size);
        max-width: 90%;
    }

    .file-input-label {
        overflow-x: auto;
    }

    .file-input {
        max-width: 100%;
    }

    .file-input::file-selector-button {
        border: none;
        background: #0001;
        font-size: var(--reactive-font-size);
        border: 1px solid;
    }

    .settings-button {
        cursor: pointer;
        background: transparent;
        border: none !important;
        /* border: 1px solid; */
        box-sizing: border-box;
        background-color: #0001;
        border-radius: 10px;
        margin: 0;
        padding: 3px;
        font: inherit;
        min-width: fit-content;
    }

    .spellbook-item {
        display: flex;
        gap: calc(var(--unit-width) * 2);
        justify-content: space-between;
        margin-bottom: calc(var(--unit-height) * 1);
    }

    .spellbook-button {
        cursor: pointer;
        background: transparent;
        border: none !important;
        margin-left: 5px;
        padding: 0;
        font: inherit;
        font-style: italic;
        /* text-decoration: underline; */
    }

    .container-after {
        display: block;
        flex-shrink: 0;
        height: calc(var(--unit-height) * 10);
    }

    .hr-break {
        margin: 0;
        border-color: rgb(24, 24, 24);
        color: rgb(24, 24, 24);
        border: 1px solid;
    }
</style>
