// src/components/SquareButton.jsx

import { ButtonType, ButtonImages } from '../constants/buttonType';
import { Link } from 'wouter';
import '../css/square-button.css';

export default function SquareButton({ buttonType, onClick, xPosition, yPosition, isLink, linkTo }) {
    // Get image path based on button type
    const getImagePath = (type) => {
        const imageName = ButtonImages[type] || ButtonImages[ButtonType.HOME];
        return `assets/img/buttons/${imageName}`;
    };

    return (
        <>
            {isLink ? (
                <Link to={linkTo} className='interact square-button' style={{ left: `calc(var(--unit-width) * ${xPosition})`, top: `calc(var(--unit-height) * ${yPosition})` }}>
                    <img className={`button-img`} src={getImagePath(buttonType)} alt={`${buttonType} button`} draggable={false} />
                </Link>
            ) : (
                <button className='interact square-button' onClick={onClick} style={{ left: `calc(var(--unit-width) * ${xPosition})`, top: `calc(var(--unit-height) * ${yPosition})` }}>
                    <img className={`button-img`} src={getImagePath(buttonType)} alt={`${buttonType} button`} draggable={false} />
                </button>
            )}
        </>
    );
}

// src/components/SquareButton.svelte
<script>
    import { ButtonType, ButtonImages } from '../constants/buttonType';
    import '../css/square-button.css';

    let { buttonType, onClick, xPosition, yPosition, isLink, linkTo, rightPage = false } = $props();

    function getImagePath(type) {
        const imageName = ButtonImages[type] || ButtonImages[ButtonType.HOME];
        return `assets/img/buttons/${imageName}`;
    }

    let positionStyle = $derived(
        `left: calc(var(--unit-width) * ${xPosition}); top: calc(var(--unit-height) * ${yPosition});`
    );
</script>

{#if isLink}
    <a href={linkTo} class="interact square-button" class:right-page-offset-px={rightPage} style={positionStyle}  >
        <img class="button-img" src={getImagePath(buttonType)} alt={`${buttonType} button`} draggable="false" />
    </a>
{:else}
    <button class="interact square-button" class:right-page-offset-px={rightPage} onclick={onClick} style={positionStyle}>
        <img class="button-img" src={getImagePath(buttonType)} alt={`${buttonType} button`} draggable="false" />
    </button>
{/if}
